# Generated by Django 5.2.7 on 2025-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da empresa')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do contato')),
                ('niche', models.CharField(max_length=30, verbose_name='Nicho')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato')),
                ('has_whatsapp', models.BooleanField(default=True, verbose_name='Tem Whatsapp?')),
                ('website_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link do site')),
                ('lead_origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem do lead')),
                ('contact_status', models.CharField(choices=[('new', 'Novo'), ('pending', 'Pendente'), ('attempting_contact', 'Tentativa de Contato'), ('in_contact', 'Em Contato'), ('qualified', 'Qualificado'), ('development', 'Desenvolvimento / Prova'), ('proposal_sent', 'Proposta Enviada'), ('closed', 'Fechado (Cliente)'), ('unqualified', 'Desqualificado')], default='new', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('company_name',),
            },
        ),
    ]
