# Generated by Django 5.2.7 on 2025-10-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='lead',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Retorno'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_status',
            field=models.CharField(choices=[('new', 'Novo'), ('pending', 'Pendente'), ('on_hold_scheduled', 'Em Espera (Agendado)'), ('attempting_contact', 'Tentativa de Contato'), ('in_contact', 'Em Contato'), ('qualified', 'Qualificado'), ('development', 'Desenvolvimento / Prova'), ('proposal_sent', 'Proposta Enviada'), ('closed', 'Fechado (Cliente)'), ('unqualified', 'Desqualificado')], default='new', max_length=50, verbose_name='Status'),
        ),
    ]
